[package]
name = "moon_bun_lang"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_lang = { path = "../../core/lang" }
cached = { workspace = true }
miette = { workspace = true }
nodejs_package_json = "0.3.1"
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }
tracing = { workspace = true }
yarn-lock-parser = "0.10.0"

[lints]
workspace = true
