[package]
name = "moon_remote"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_action = { path = "../action" }
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_task = { path = "../task" }
async-trait = { workspace = true }
bazel-remote-apis = { version = "0.14.0", features = ["serde"] }
bincode = "1.3.3"
chrono = { workspace = true }
miette = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
rustc-hash = { workspace = true }
scc = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
starbase_utils = { workspace = true, features = ["glob", "json"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = "0.26.1"
tonic = { version = "0.12.3", default-features = false, features = [
    "channel",
    "gzip",
    "tls",
    "tls-native-roots",
] }
tracing = { workspace = true }
zstd = "0.13.2"

[lints]
workspace = true
